import { useQuery } from "@tanstack/react-query";
import { Link, useLocation } from "wouter";
import { ArrowLeft, BookOpen, Compass, Film, Flame, GitBranch, Layers, Sparkles } from "lucide-react";

interface Item { id: string; title: string; thumbnail: string | null; creatorName: string; creatorAvatar: string | null; pageCount: number; status: string; createdAt: string; userId: string; projectType?: string; viewCount?: number }
interface LibraryResponse { comics: Item[]; total: number; page: number; totalPages: number }

const icons: Record<string, typeof BookOpen> = { comic: BookOpen, vn: Film, cyoa: GitBranch, hop: Film, card: Layers, motion: Film };
const labels: Record<string, string> = { comic: "COMIC", vn: "VISUAL NOVEL", cyoa: "CYOA", hop: "HOP", card: "CARDS", motion: "MOTION" };

function Card({ item, large = false }: { item: Item; large?: boolean }) {
  const Icon = icons[item.projectType || ""] || Film;
  return <Link href={`/streaming/title/${item.id}`} className="group block"><article className="overflow-hidden rounded-2xl border border-white/10 bg-[#101010] transition duration-300 group-hover:-translate-y-1 group-hover:border-[#f0ae2e]/45"><div className={large ? "aspect-video" : "aspect-[3/4]"}>{item.thumbnail ? <img src={item.thumbnail} alt={item.title} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center bg-[#171717]"><Icon className="h-10 w-10 text-zinc-700" /></div>}</div><div className="border-t border-white/[0.07] p-3.5"><div className="mb-2 flex items-center gap-2 text-[10px] font-black tracking-[0.14em] text-[#f0ae2e]"><Icon className="h-3.5 w-3.5" />{labels[item.projectType || ""] || "PRESS START"}</div><h3 className="truncate text-sm font-bold">{item.title}</h3><p className="mt-1 truncate text-xs text-zinc-500">{item.creatorName}</p></div></article></Link>;
}

export default function StreamingDiscovery() {
  const [location] = useLocation();
  const mode = location.includes("trending") ? "trending" : location.includes("explore") ? "explore" : "discover";
  const config = mode === "trending" ? { title: "Trending", subtitle: "What the Press Start audience is opening right now.", sort: "popular", Icon: Flame } : mode === "explore" ? { title: "Explore", subtitle: "Move across formats and discover creators throughout the ecosystem.", sort: "newest", Icon: Compass } : { title: "Discover", subtitle: "A curated cross-section of new work, popular releases and every creator format.", sort: "popular", Icon: Sparkles };

  const primary = useQuery<LibraryResponse>({ queryKey: ["ps-streaming", mode, "primary"], queryFn: async () => { const q = new URLSearchParams({ page: "1", limit: "50", sort: config.sort }); const r = await fetch(`/api/community/library?${q}`); if (!r.ok) throw new Error("Failed to load"); return r.json(); } });
  const newest = useQuery<LibraryResponse>({ queryKey: ["ps-streaming", mode, "new"], queryFn: async () => { const q = new URLSearchParams({ page: "1", limit: "24", sort: "newest" }); const r = await fetch(`/api/community/library?${q}`); if (!r.ok) throw new Error("Failed to load"); return r.json(); } });
  const items = primary.data?.comics || [];
  const hero = items[0];

  return <div className="min-h-screen bg-[#050505] text-white"><header className="sticky top-0 z-40 border-b border-white/[0.07] bg-black/80 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1680px] items-center gap-4 px-5 sm:px-8"><Link href="/streaming" className="grid h-9 w-9 place-items-center rounded-full border border-white/10 text-zinc-400 transition hover:border-[#f0ae2e]/45 hover:text-white"><ArrowLeft className="h-4 w-4" /></Link><div><div className="text-[10px] font-black tracking-[0.2em] text-[#f0ae2e]">PRESS START STREAMING</div><div className="text-sm font-black uppercase">{config.title}</div></div></div></header><main className="mx-auto max-w-[1680px] px-5 py-10 sm:px-8"><div className="flex items-center gap-4"><div className="grid h-12 w-12 place-items-center rounded-2xl border border-[#f0ae2e]/30 bg-[#f0ae2e]/10"><config.Icon className="h-6 w-6 text-[#f0ae2e]" /></div><div><h1 className="text-4xl font-black tracking-[-0.035em] sm:text-5xl">{config.title}</h1><p className="mt-2 text-sm text-zinc-500 sm:text-base">{config.subtitle}</p></div></div>{hero && <Link href={`/streaming/title/${hero.id}`} className="group relative mt-10 block min-h-[390px] overflow-hidden rounded-[28px] border border-white/10 bg-[#101010]"><div className="absolute inset-0">{hero.thumbnail && <img src={hero.thumbnail} alt="" className="h-full w-full object-cover opacity-55 transition duration-700 group-hover:scale-[1.02]" />}<div className="absolute inset-0 bg-gradient-to-r from-black via-black/80 to-transparent" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent" /></div><div className="relative flex min-h-[390px] max-w-2xl flex-col justify-end p-7 sm:p-10"><div className="text-[10px] font-black tracking-[0.18em] text-[#f0ae2e]">FEATURED DISCOVERY</div><h2 className="mt-3 text-4xl font-black tracking-[-0.035em] sm:text-5xl">{hero.title}</h2><p className="mt-3 text-sm text-zinc-400">{hero.creatorName}</p></div></Link>}<section className="mt-12"><h2 className="mb-5 text-2xl font-black">{mode === "trending" ? "Most Popular" : "For Discovery"}</h2><div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">{items.slice(1).map(i => <Card key={i.id} item={i} />)}</div></section>{mode !== "trending" && <section className="mt-12"><h2 className="mb-5 text-2xl font-black">Just Added</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{(newest.data?.comics || []).slice(0, 8).map(i => <Card key={i.id} item={i} large />)}</div></section>}</main></div>;
}
