import type { BrushProfile } from "./types";
import { PRESSURE_PRESETS } from "./types";

/**
 * INKBLADE default brush family.
 * All brushes use raw stylus data and identical input handling — only their
 * rendering parameters differ. Same pen → same line, just different character.
 */
export const INKBLADE_BRUSHES: BrushProfile[] = [
  {
    id: "core",
    name: "Core",
    size: 6,
    minPressure: 0.0,
    maxPressure: 1.0,
    pressureCurve: PRESSURE_PRESETS.medium,
    pressureToSize: 0.7,
    pressureToOpacity: 0.0,
    stabilization: "standard",
    taperStart: 0.2,
    taperEnd: 0.4,
    thinning: 0.5,
    smoothing: 0.5,
    streamline: 0.5,
    tiltToEllipse: true,
    textureGrain: 0.0,
    color: "#000000",
    opacity: 1.0,
  },
  {
    id: "rough",
    name: "Rough",
    size: 8,
    minPressure: 0.0,
    maxPressure: 1.0,
    pressureCurve: PRESSURE_PRESETS.medium,
    pressureToSize: 0.6,
    pressureToOpacity: 0.3,
    stabilization: "light",
    taperStart: 0.0,
    taperEnd: 0.0,
    thinning: 0.7,
    smoothing: 0.2,
    streamline: 0.3,
    tiltToEllipse: true,
    textureGrain: 0.6,
    color: "#000000",
    opacity: 1.0,
  },
  {
    id: "bold",
    name: "Bold",
    size: 14,
    minPressure: 0.05,
    maxPressure: 1.0,
    pressureCurve: PRESSURE_PRESETS.heavy,
    pressureToSize: 0.4,
    pressureToOpacity: 0.0,
    stabilization: "standard",
    taperStart: 0.1,
    taperEnd: 0.1,
    thinning: 0.3,
    smoothing: 0.6,
    streamline: 0.6,
    tiltToEllipse: false,
    textureGrain: 0.0,
    color: "#000000",
    opacity: 1.0,
  },
  {
    id: "drift",
    name: "Drift",
    size: 4,
    minPressure: 0.0,
    maxPressure: 0.8,
    pressureCurve: PRESSURE_PRESETS.light,
    pressureToSize: 0.9,
    pressureToOpacity: 0.5,
    stabilization: "heavy",
    taperStart: 0.6,
    taperEnd: 0.8,
    thinning: 0.85,
    smoothing: 0.85,
    streamline: 0.7,
    tiltToEllipse: true,
    textureGrain: 0.0,
    color: "#000000",
    opacity: 0.9,
  },
  {
    id: "graff",
    name: "Graff",
    size: 22,
    minPressure: 0.1,
    maxPressure: 1.0,
    pressureCurve: PRESSURE_PRESETS.medium,
    pressureToSize: 0.3,
    pressureToOpacity: 0.4,
    stabilization: "light",
    taperStart: 0.0,
    taperEnd: 0.2,
    thinning: 0.2,
    smoothing: 0.3,
    streamline: 0.4,
    tiltToEllipse: true,
    textureGrain: 0.4,
    color: "#000000",
    opacity: 0.95,
  },
  {
    id: "cutline",
    name: "Cutline",
    size: 3,
    minPressure: 0.0,
    maxPressure: 1.0,
    pressureCurve: PRESSURE_PRESETS.wacom,
    pressureToSize: 0.5,
    pressureToOpacity: 0.0,
    stabilization: "heavy",
    taperStart: 0.5,
    taperEnd: 0.5,
    thinning: 0.6,
    smoothing: 0.9,
    streamline: 0.85,
    tiltToEllipse: false,
    textureGrain: 0.0,
    color: "#000000",
    opacity: 1.0,
  },
];

export function getBrush(id: string): BrushProfile {
  return INKBLADE_BRUSHES.find(b => b.id === id) ?? INKBLADE_BRUSHES[0];
}
